service:
  name: lilo-sls-timeout

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'ryan'}
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-01b11e30549f88170
    subnetIds:
      - subnet-0cba10d6dcf33c533

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

functions:
  queryTimeout:
    handler: src/handlers/queryTimeout.handler
    events:
      - http:
          method: GET
          path: /test/timeout/query/{type}/{cus_id}
  queryTimeoutPost:
    handler: src/handlers/queryTimeout.handler
    events:
      - http:
          method: POST
          path: /post/test/timeout/query
  recordRatingCopy:
    handler: src/handlers/recordRatingCopy.handler
    events:
      - http:
          method: GET
          path: /test/timeout/record-rating-copy
    timeout: 7
custom:
  bundle:
    linting: false
